### ISSUE TITLE
[RFC] Decouple from translation library

### ISSUE THREAD

**Issue by benatespina** [FriendsOfECMAScript/ReactI18nRouting#14]
Currently, we only support Yahoo's `react-intl`, it's the most popular library to make things work in React around translations. However, there are another good ~~better~~ alternatives like *LinguiJs* (check out [this](https://lingui.js.org/misc/react-intl.html) information if you don't know what library is).

So, the idea behind this issue is to become our library more decoupled from translations libraries allowing the usage of our favorite library.

**Comment by gorkalaucirica** [comment]
After refactoring to new Context API in #13 we got rid of `react-intl` as well as `react-redux`. With that, you can use any translation or state management library.

You can see how peerDependencies were removed [here](https://github.com/FriendsOfECMAScript/ReactI18nRouting/pull/13/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R126)

**Comment by benatespina** [comment]
Yeah, it's true! Awesome!
